; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
; 160 MHZ
board_build.f_cpu = 160000000L 
; 80 MHZ 
board_build.f_flash = 80000000L
;Split flash, 1MB(OTA) , 1MB(app), 2MB(SPIFFS), 4KB(EEPROM), 4KB(rfLOCAL), 12KB (WIFI CONFIG) 
board_build.ldscript = eagle.flash.4m2m.ld 
; lower memory
build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -D VTABLES_IN_FLASH
